apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-{{.Chart.Name}}-deployment
  namespace: otel-examples
  labels:
    app.kubernetes.io/name: {{.Chart.Name}}
    app.kubernetes.io/instance: {{.Chart.Name}}
    app.kubernetes.io/version: {{.Chart.AppVersion}}
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{.Chart.Name}}
      app.kubernetes.io/instance: {{.Chart.Name}}
    template:
      metadata:
        labels:
          app.kubernetes.io/name: {{.Chart.Name}}
          app.kubernetes.io/instance: {{.Chart.Name}}
      spec:
        containers:
          - name: {{.Chart.Name}}
            image: {{.Values.image.repository}}:{{.Values.image.tag}}
            imagePullPolicy: Always
            ports:
              - name: http
                containerPort: 8080
              - name: https
                containerPort: 8081
            resources:
              requests:
                memory: "512Mi"
                cpu: "250m"
              limits:
                memory: "1Gi"
                cpu: "500m"