apiVersion: v1
kind: Service
metadata:
  name: otel-collector-api-connect-service
  namespace: otel-examples
spec:
  selector:
    app: otel-collector-api-connect
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
    - protocol: TCP
      port: 8081
      targetPort: 8081
