apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: otel
spec:
  type: LoadBalancer
  selector:
    app: otel-collector
  ports:
  - protocol: TCP
    port: 4317
    targetPort: 4317
