replicaCount: 1

namespace: otel-examples

image:
  repository: kkelvekar/otelcollectorapiconnect
  pullPolicy: IfNotPresent
  tag: "1.0.2"

service:
  type: LoadBalancer
  port: 8080
  protocol: TCP

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi