replicaCount: 1

namespace: otel-examples

image:
  repository: kkelvekar/otelcollectorapiconnect
  pullPolicy: IfNotPresent
  tag: "1.9.0"

service:
  type: ClusterIP
  hostport: 8080
  containerport: 8080
  protocol: TCP

resources:
  limits:
    cpu: 400m
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 512Mi